###############################################################################
#
# Services configuration file
#
# Created by: Nagios CCM 3.0.6
# Date:       2020-07-19 15:54:21
# Version:    Nagios Core 4.x
#
# --- DO NOT EDIT THIS FILE BY HAND --- 
# Nagios CCM will overwrite all manual settings during the next update if you 
# would like to edit files manually, place them in the 'static' directory or 
# import your configs into the CCM by placing them in the 'import' directory.
#
###############################################################################

define service {
    host_name                {{ fqdn }}
    service_description      CPU Usage
    use                      xiwizard_ncpa_service
    check_command            check_xi_ncpa!-t 'NIm7t2DM5sdK79lE' -P 5693 -M cpu/percent -w '20' -c '40' -q 'aggregate=avg'
    max_check_attempts       5
    check_interval           5
    retry_interval           1
    check_period             xi_timeperiod_24x7
    notification_interval    60
    notification_period      xi_timeperiod_24x7
    contacts                 nagiosadmin
    _xiwizard                ncpa
    register                 1
}

define service {
    host_name                {{ fqdn }}
    service_description      Disk Usage on /
    use                      xiwizard_ncpa_service
    check_command            check_xi_ncpa!-t 'NIm7t2DM5sdK79lE' -P 5693 -M 'disk/logical/|' -w '70' -c '90'
    max_check_attempts       5
    check_interval           5
    retry_interval           1
    check_period             xi_timeperiod_24x7
    notification_interval    60
    notification_period      xi_timeperiod_24x7
    contacts                 nagiosadmin
    _xiwizard                ncpa
    register                 1
}

define service {
    host_name                {{ fqdn }}
    service_description      Disk Usage on /boot
    use                      xiwizard_ncpa_service
    check_command            check_xi_ncpa!-t 'NIm7t2DM5sdK79lE' -P 5693 -M 'disk/logical/|boot' -w '70' -c '90'
    max_check_attempts       5
    check_interval           5
    retry_interval           1
    check_period             xi_timeperiod_24x7
    notification_interval    60
    notification_period      xi_timeperiod_24x7
    contacts                 nagiosadmin
    _xiwizard                ncpa
    register                 1
}

define service {
    host_name                {{ fqdn }}
    service_description      Disk Usage on /snap/core/7270
    use                      xiwizard_ncpa_service
    check_command            check_xi_ncpa!-t 'NIm7t2DM5sdK79lE' -P 5693 -M 'disk/logical/|snap|core|7270' -w '70' -c '90'
    max_check_attempts       5
    check_interval           5
    retry_interval           1
    check_period             xi_timeperiod_24x7
    notification_interval    60
    notification_period      xi_timeperiod_24x7
    contacts                 nagiosadmin
    _xiwizard                ncpa
    register                 1
}

define service {
    host_name                {{ fqdn }}
    service_description      Disk Usage on /snap/core/9665
    use                      xiwizard_ncpa_service
    check_command            check_xi_ncpa!-t 'NIm7t2DM5sdK79lE' -P 5693 -M 'disk/logical/|snap|core|9665' -w '70' -c '90'
    max_check_attempts       5
    check_interval           5
    retry_interval           1
    check_period             xi_timeperiod_24x7
    notification_interval    60
    notification_period      xi_timeperiod_24x7
    contacts                 nagiosadmin
    _xiwizard                ncpa
    register                 1
}

define service {
    host_name                {{ fqdn }}
    service_description      Disk Usage on /sys/fs/cgroup/unified
    use                      xiwizard_ncpa_service
    check_command            check_xi_ncpa!-t 'NIm7t2DM5sdK79lE' -P 5693 -M 'disk/logical/|sys|fs|cgroup|unified' -w '70' -c '90'
    max_check_attempts       5
    check_interval           5
    retry_interval           1
    check_period             xi_timeperiod_24x7
    notification_interval    60
    notification_period      xi_timeperiod_24x7
    contacts                 nagiosadmin
    _xiwizard                ncpa
    register                 1
}

define service {
    host_name                {{ fqdn }}
    service_description      Disk Usage on /zp21
    use                      xiwizard_ncpa_service
    check_command            check_xi_ncpa!-t 'NIm7t2DM5sdK79lE' -P 5693 -M 'disk/logical/|zp21' -w '70' -c '90'
    max_check_attempts       5
    check_interval           5
    retry_interval           1
    check_period             xi_timeperiod_24x7
    notification_interval    60
    notification_period      xi_timeperiod_24x7
    contacts                 nagiosadmin
    _xiwizard                ncpa
    register                 1
}

define service {
    host_name                {{ fqdn }}
    service_description      ens33 Bandwidth - Inbound
    use                      xiwizard_ncpa_service
    check_command            check_xi_ncpa!-t 'NIm7t2DM5sdK79lE' -P 5693 -M 'interface/ens33/bytes_recv' -d -u M -w '10' -c '100'
    max_check_attempts       5
    check_interval           5
    retry_interval           1
    check_period             xi_timeperiod_24x7
    notification_interval    60
    notification_period      xi_timeperiod_24x7
    contacts                 nagiosadmin
    _xiwizard                ncpa
    register                 1
}

define service {
    host_name                {{ fqdn }}
    service_description      ens33 Bandwidth - Outbound
    use                      xiwizard_ncpa_service
    check_command            check_xi_ncpa!-t 'NIm7t2DM5sdK79lE' -P 5693 -M 'interface/ens33/bytes_sent' -d -u M -w '10' -c '100'
    max_check_attempts       5
    check_interval           5
    retry_interval           1
    check_period             xi_timeperiod_24x7
    notification_interval    60
    notification_period      xi_timeperiod_24x7
    contacts                 nagiosadmin
    _xiwizard                ncpa
    register                 1
}

define service {
    host_name                {{ fqdn }}
    service_description      Memory Usage
    use                      xiwizard_ncpa_service
    check_command            check_xi_ncpa!-t 'NIm7t2DM5sdK79lE' -P 5693 -M memory/virtual -u 'Gi' -w '50' -c '80'
    max_check_attempts       5
    check_interval           5
    retry_interval           1
    check_period             xi_timeperiod_24x7
    notification_interval    60
    notification_period      xi_timeperiod_24x7
    contacts                 nagiosadmin
    _xiwizard                ncpa
    register                 1
}

define service {
    host_name                {{ fqdn }}
    service_description      Swap Usage
    use                      xiwizard_ncpa_service
    check_command            check_xi_ncpa!-t 'NIm7t2DM5sdK79lE' -P 5693 -M memory/swap -u 'Gi' -w '5' -c '10'
    max_check_attempts       5
    check_interval           5
    retry_interval           1
    check_period             xi_timeperiod_24x7
    notification_interval    60
    notification_period      xi_timeperiod_24x7
    contacts                 nagiosadmin
    _xiwizard                ncpa
    register                 1
}

define service {
    host_name                {{ fqdn }}
    service_description      User Count
    use                      xiwizard_ncpa_service
    check_command            check_xi_ncpa!-t 'NIm7t2DM5sdK79lE' -P 5693 -M user/count -w '2' -c '4'
    max_check_attempts       5
    check_interval           5
    retry_interval           1
    check_period             xi_timeperiod_24x7
    notification_interval    60
    notification_period      xi_timeperiod_24x7
    contacts                 nagiosadmin
    _xiwizard                ncpa
    register                 1
}

###############################################################################
#
# Services configuration file
#
# END OF FILE
#
###############################################################################
